apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - name: app1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared
          mountPath: /usr/share/nginx/html
    - name: app2
      image: nginx
      env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: multi-config
              key: port
      ports:
        - containerPort: 50
      volumeMounts:
        - name: shared
          mountPath: /usr/share/nginx/html
  volumes:
    - name: shared
      emptyDir: {}
