apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
        upstream nodeapps {
            server nodeapp1-service:80;
            server nodeapp2-service:80;
        }

        server {
            listen 80;

            location / {
                proxy_pass http://nodeapps;
            }
        }
    }
