apiVersion: v1
kind: Pod
metadata:
  name: nodeapp1
  labels:
    app: nodeapp1
spec:
  containers:
    - name: nodeapp1
      image: abdlrhman00/nodeapp1:latest
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp1-service
spec:
  selector:
    app: nodeapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
