   apiVersion: v1
   kind: Pod
   metadata:
     name: nginx-pod
   spec:
     containers:
       - name: nginx
         image: nginx:latest
         volumeMounts:
           - name: config
             mountPath: /etc/nginx/nginx.conf
             subPath: nginx.conf
           - name: html
             mountPath: /usr/share/nginx/html
     volumes:
       - name: config
         configMap:
           name: nginx-config
       - name: html
         persistentVolumeClaim:
           claimName: pvc-nginx