   apiVersion: v1
   kind: PersistentVolume
   metadata:
     name: pv-nginx
   spec:
     capacity:
       storage: 1Gi
     accessModes:
       - ReadWriteOnce
     hostPath:
       path: "/data/nginx"